#!/bin/bash

# Resolve dir, from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
bashsource="${BASH_SOURCE[0]}"
while [ -h "$bashsource" ]; do 
  dir="$( cd -P "$( dirname "$bashsource" )" && pwd )"
  bashsource="$(readlink "$bashsource")"
  [[ $bashsource != /* ]] && bashsource="$dir/$bashsource"
done

dir="$( cd -P "$( dirname "$bashsource" )" && pwd )"

# Scripts 
"$dir/scripts/lint-prepared-commit" $@

if [[ $? != 0 ]]; then 
  exit 1
fi

exit 0
